# taplo: schema=https://starship.rs/config-schema.json

add_newline = false
command_timeout = 1000
format = "$env_var$all"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = false

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"
style = "dim white"

[username]
disabled = false
show_always = true
format = "[$user]($style) in "

[hostname]
disabled = true
